### ISSUE TITLE
spring-boot-starter-thymeleaf not needed ?

### ISSUE THREAD

**Issue by clementSabattie** [serlesen/fullstack-oauth2#1]
Because you use Angular as FrontEnd, I think spring-boot-starter-thymeleaf can be removed

What do you think ?

https://github.com/serlesen/fullstack-oauth2/blob/821549d3301ed1312169035a7695b63cc07c40e6/backend/pom.xml#L34C36-L34C45

**Comment by serlesen** [comment]
Yes, you're right.
I've added Thymeleaf because in the video (https://youtu.be/yp28g5AJczM), I first explain the OAuth2 workflow with a Server-Side Rendering Frontend with Thymeleaf. 
The final version is with Angular but I didn't remove the dependency.

**Comment by clementSabattie** [comment]
Yes thanks a lot for the video.
I have already seen it.
